spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sensorDatadb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    roo: INFO

